# Generated by Django 5.2.9 on 2025-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
