# Generated by Django 5.2.9 on 2026-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pendingorder_coupon_code_pendingorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
