# Generated by Django 5.2.9 on 2025-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_otp_sent_at_user_otp_sent_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_otp_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_sent_count',
        ),
    ]
