# Generated by Django 5.2.9 on 2025-12-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_cod', models.BooleanField(default=True)),
                ('allow_order_cancel', models.BooleanField(default=True)),
                ('allow_order_return', models.BooleanField(default=True)),
            ],
        ),
    ]
