# Generated by Django 5.2.9 on 2025-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_min_amount',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
