# Generated by Django 5.2.9 on 2026-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
