# Generated by Django 5.2.9 on 2025-12-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminotp',
            options={'get_latest_by': 'created_at'},
        ),
    ]
