# Generated by Django 5.2.9 on 2026-06-16 18:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
