# Generated by Django 5.2.9 on 2026-06-16 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
