# Generated by Django 5.2.9 on 2025-12-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
