# Generated by Django 5.2.9 on 2025-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat Amount')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Default Offer', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
