# Generated by Django 5.2.9 on 2026-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_admin_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
