# Generated by Django 5.2.9 on 2026-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_admin_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cf_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
