# Generated by Django 5.2.9 on 2026-03-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cf_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cf_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
