# Generated by Django 5.2.9 on 2025-12-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Product Number / SKU', max_length=50, null=True, unique=True),
        ),
    ]
