# Generated by Django 5.2.9 on 2025-12-31 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_options_remove_offer_discount_percentage_and_more'),
        ('products', '0003_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='offers.offer'),
        ),
    ]
